import 'package:animated_text_kit/animated_text_kit.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class Section_four extends StatefulWidget {
  Section_four({Key? key}) : super(key: key);

  @override
  _Section_fourState createState() => _Section_fourState();
}

class _Section_fourState extends State<Section_four> {
  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        image: DecorationImage(
          fit: BoxFit.cover,
          image: AssetImage(
            'images/2.jpg',
          ),
        ),
      ),
      height: 320,
      child: Container(
        color: Colors.white.withOpacity(0.5),
        margin: EdgeInsets.only(top: 20, left: 10, right: 10, bottom: 20),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          children: <Widget>[
            // const SizedBox(width: 10.0, height: 100.0),
            Row(
              children: [
                const Text(
                  'Book us for ',
                  style: TextStyle(fontSize: 43.0),
                ),
                Icon(Icons.arrow_forward),
              ],
            ),
            // const SizedBox(width: 10.0, height: 100.0),
            Row(
              children: [
                SizedBox(
                  width: MediaQuery.of(context).size.width * 0.1,
                ),
                DefaultTextStyle(
                  style: const TextStyle(
                      fontSize: 40.0,
                      fontFamily: 'Horizon',
                      color: Colors.teal),
                  child: AnimatedTextKit(
                    animatedTexts: [
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                      RotateAnimatedText('Birthday Party'),
                      RotateAnimatedText('Anniversary'),
                      RotateAnimatedText('Meetings'),
                      RotateAnimatedText('Date'),
                      RotateAnimatedText('Kitty Party'),
                    ],
                    onTap: () {
                      print("Tap Event");
                    },
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
